[package]
name = "plc_logger"
version = "0.1.0"
authors = ["RUMFLUKICHED"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
config = "0.10"
chrono = "0.4"
ctrlc = "3.1.4"
clap = "2.33.0"